# -*- coding: utf-8 -*-
"""CV LAB-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Vfj6SRENhAKQmR277w8nJqJYJ0Sek1L
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

def show_comparison(original, blur1, blur2, blur3, title1='Blurred image 1', title2='Blurred image 2', title3='Blurred image 3'):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original)
  plt.title('Original image')
  plt.subplot(2,2,2)
  plt.imshow(blur1)
  plt.title(title1)
  plt.subplot(2,2,3)
  plt.imshow(blur2)
  plt.title(title2)
  plt.subplot(2,2,4)
  plt.imshow(blur3)
  plt.title(title3)
  plt.show()

import cv2
import matplotlib.pyplot as plt

# Read the original grayscale image
img = cv2.imread("/content/IMAGE.jpeg", cv2.IMREAD_GRAYSCALE)

if img is None:
    print("Error: Could not load the image.")
else:
    print(f"Image loaded successfully")

    # Apply Average Filters
    average_3x3 = cv2.blur(img, (3, 3))
    average_5x5 = cv2.blur(img, (5, 5))
    average_7x7 = cv2.blur(img, (7, 7))

    # Display results
    plt.figure(figsize=(12, 8))

    plt.subplot(2, 2, 1)
    plt.imshow(img, cmap="gray")
    plt.title("Original grayscale image")
    plt.axis("off")

    plt.subplot(2, 2, 2)
    plt.imshow(average_3x3, cmap="gray")
    plt.title("average filter(3*3)")
    plt.axis("off")

    plt.subplot(2, 2, 3)
    plt.imshow(average_5x5, cmap="gray")
    plt.title("average filter(5*5)")
    plt.axis("off")

    plt.subplot(2, 2, 4)
    plt.imshow(average_7x7, cmap="gray")
    plt.title("average filter(7*7)")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

def average_filter(img, k):
    p = 0
    s = 1
    kernel = np.ones((k, k)) * (1 / (k * k))
    m, n = img.shape

    filtered_img = np.zeros((m - k + 1, n - k + 1))

    for i in range(0, m - k + 1, s):
        for j in range(0, n - k + 1, s):

            filtered_img[i, j] = np.sum(
                kernel * img[i:i+k, j:j+k]
            )

    return filtered_img



img = Image.open("/content/IMAGE2.jpg")

gray_img = img.convert("L")
img_array = np.array(gray_img)
blur_3 = average_filter(img_array, 3)
blur_5 = average_filter(img_array, 5)
blur_7 = average_filter(img_array, 7)
blur_11 = average_filter(img_array, 11)
plt.figure(figsize=(12, 10))
plt.subplot(2, 3, 1)
plt.imshow(img)
plt.title("Original Image")
plt.axis("off")
plt.subplot(2, 3, 2)
plt.imshow(img_array, cmap="gray")
plt.title("Gray Scale Image")
plt.axis("off")

plt.subplot(2, 3, 3)
plt.imshow(blur_3, cmap="gray")
plt.title("Average Filter 3x3")
plt.axis("off")

plt.subplot(2, 3, 4)
plt.imshow(blur_5, cmap="gray")
plt.title("Average Filter 5x5")
plt.axis("off")

plt.subplot(2, 3, 5)
plt.imshow(blur_7, cmap="gray")
plt.title("Average Filter 7x7")
plt.axis("off")

plt.subplot(2, 3, 6)
plt.imshow(blur_11, cmap="gray")
plt.title("Average Filter 11x11")
plt.axis("off")

plt.tight_layout()
plt.show()

